package models

type Jurnal struct {
	ID                    int      `bson:"_id" json:"_id"`
	JudulArtikel          string   `bson:"judul_artikel" json:"judul_artikel"`
	NamaJurnal            string   `bson:"nama_jurnal" json:"nama_jurnal"`
	Tanggal               string   `bson:"tanggal" json:"tanggal"`
	Semester              string   `bson:"semester" json:"semester"`
	TahunAjaran           string   `bson:"tahun_ajaran" json:"tahun_ajaran"`
  TahunData                string `bson:"tahun_data" json:"tahun_data"`
	Akreditasi            string   `bson:"akreditasi" json:"akreditasi"`
	CreatedAt             string   `bson:"created_at" json:"created_at"`
	IsValid               string   `bson:"isValid" json:"isValid"`
	TbName                string   `bson:"tbName" json:"tbName"`
	PrimaryKey            string   `bson:"primaryKey" json:"primaryKey"`
	WaktuPelaksanaan      string   `bson:"waktu_pelaksanaan" json:"waktu_pelaksanaan"`
	NamaDosen             string   `bson:"nama_dosen" json:"nama_dosen"`
	KodeProdi             string   `bson:"kode_prodi" json:"kode_prodi"`
	NamaJurusan           string   `bson:"nama_jurusan" json:"nama_jurusan"`
	NamaFakultas          string   `bson:"nama_fakultas" json:"nama_fakultas"`
	IdSinta               string   `bson:"id_sinta" json:"id_sinta"`
	Authors               string   `bson:"authors" json:"authors"`
	Sitasi                string   `bson:"sitasi" json:"sitasi"`
	VolumeJurnal          string   `bson:"volume_jurnal" json:"volume_jurnal"`
	NomorJurnal           string   `bson:"nomor_jurnal" json:"nomor_jurnal"`
	HalamanAwal           string   `bson:"halaman_awal" json:"halaman_awal"`
	HalamanAkhir          string   `bson:"halaman_akhir" json:"halaman_akhir"`
	PIssn                 string   `bson:"P_ISSN" json:"P_ISSN"`
	EIssn                 string   `bson:"E_ISSN" json:"E_ISSN"`
	Doi                   string   `bson:"DOI" json:"DOI"`
	Penerbit              string   `bson:"penerbit" json:"penerbit"`
	FileUpload            string   `bson:"file_upload" json:"file_upload"`
	AlamatWebJurnal       string   `bson:"alamat_web_jurnal" json:"alamat_web_jurnal"`
	UrlDokumen            string   `bson:"url_dokumen" json:"url_dokumen"`
	UrlPeerReview         string   `bson:"url_peer_review" json:"url_peer_review"`
	Keterangan            string   `bson:"keterangan" json:"keterangan"`
	BahasaID              string   `bson:"bahasa_id" json:"bahasa_id"`
	Sinta                 string   `bson:"sinta" json:"sinta"`
	Scope                 string   `bson:"scope" json:"scope"`
	JenisJurnal           string   `bson:"jenis_jurnal" json:"jenis_jurnal"`
	AggregationType       string   `bson:"aggregation_type" json:"aggregation_type"`
	ImpactFactor          string   `bson:"impact_factor" json:"impact_factor"`
	Satuan                string   `bson:"satuan" json:"satuan"`
	VolumeKegiatan        string   `bson:"volume_kegiatan" json:"volume_kegiatan"`
	TahunPublish          string   `bson:"tahun_publish" json:"tahun_publish"`
	Posisi                string   `bson:"posisi" json:"posisi"`
	FileSubmit            string   `bson:"file_submit" json:"file_submit"`
	FileRevisi            string   `bson:"file_revisi" json:"file_revisi"`
	FileSudahRevisi       string   `bson:"file_sudah_revisi" json:"file_sudah_revisi"`
	FileDiterima          string   `bson:"file_diterima" json:"file_diterima"`
	FileSelesaiDicetak    string   `bson:"file_selesai_dicetak" json:"file_selesai_dicetak"`
	FileTerpublikasi      string   `bson:"file_terpublikasi" json:"file_terpublikasi"`
	JmlPenulis            string   `bson:"jml_penulis" json:"jml_penulis"`
	FileHasilUjiPlagiarim string   `bson:"file_hasil_uji_plagiarim" json:"file_hasil_uji_plagiarim"`
	FilePenilaianReviewer string   `bson:"file_penilaian_reviewer" json:"file_penilaian_reviewer"`
	UpdatedAt             string   `bson:"updated_at" json:"updated_at"`
	DeletedAt             *string  `bson:"deleted_at" json:"deleted_at"`
	IsProduk              string   `bson:"is_produk" json:"is_produk"`
	ProdukPenelitianJudul string   `bson:"produk_penelitian_judul" json:"produk_penelitian_judul"`
	ProdukPenelitianID    string   `bson:"produk_penelitian_id" json:"produk_penelitian_id"`
	ProdukPengabdianJudul string   `bson:"produk_pengabdian_judul" json:"produk_pengabdian_judul"`
	ProdukPengabdianID    string   `bson:"produk_pengabdian_id" json:"produk_pengabdian_id"`
	DariApiSinta          string   `bson:"dari_api_sinta" json:"dari_api_sinta"`
	StatusLengkap         string   `bson:"status_lengkap" json:"status_lengkap"`
	Komentar              string   `bson:"komentar" json:"komentar"`
	ValidIpk              string   `bson:"valid_ipk" json:"valid_ipk"`
	ValidIpkKomentar      string   `bson:"valid_ipk_komentar" json:"valid_ipk_komentar"`
	CreateDosenID         string   `bson:"create_dosen_id" json:"create_dosen_id"`
	Indexer               []string `bson:"indexer" json:"indexer"`
	SumberProduk          string   `bson:"sumber_produk" json:"sumber_produk"`
	ProdukPenelitian      string   `bson:"produk_penelitian" json:"produk_penelitian"`
	ProdukPengabdian      string   `bson:"produk_pengabdian" json:"produk_pengabdian"`
	MahasiswaPenelitian   string   `bson:"mahasiswa_penelitian" json:"mahasiswa_penelitian"`
	AnggotaPenelitian     string   `bson:"anggota_penelitian" json:"anggota_penelitian"`
	CronTahun             string   `bson:"cron_tahun" json:"cron_tahun"`
	CronSemester          string   `bson:"cron_semester" json:"cron_semester"`
	KodeAkreditasi        string   `bson:"kode_akreditasi" json:"kode_akreditasi"`
	KodeScope             string   `bson:"kode_scope" json:"kode_scope"`
	KodeJenisJurnal       string   `bson:"kode_jenis_jurnal" json:"kode_jenis_jurnal"`
	Periode               string   `bson:"periode" json:"periode"`
	SemesterType          string   `bson:"semester_type" json:"semester_type"`
	Unit                  Unit     `bson:"unit" json:"unit"`
}
