package models

type Penelitian struct {
	ID                       int    `bson:"_id" json:"_id"`
	JudulTulisan             string `bson:"judul_tulisan" json:"judul_tulisan"`
	Tanggal                  string `bson:"tanggal" json:"tanggal"`
	CreatedAt                string `bson:"created_at" json:"created_at"`
	IsValid                  string `bson:"isValid" json:"isValid"`
	Semester                 string `bson:"semester" json:"semester"`
	TahunAjaran              string `bson:"tahun_ajaran" json:"tahun_ajaran"`
	TahunData                string `bson:"tahun_data" json:"tahun_data"`
	TbName                   string `bson:"tbName" json:"tbName"`
	PrimaryKey               string `bson:"primaryKey" json:"primaryKey"`
	WaktuPelaksanaan         string `bson:"waktu_pelaksanaan" json:"waktu_pelaksanaan"`
	NamaDosen                string `bson:"nama_dosen" json:"nama_dosen"`
	SumberDana               string `bson:"sumber_dana" json:"sumber_dana"`
	IdPenelitianBidangSub    string `bson:"id_penelitian_bidang_sub" json:"id_penelitian_bidang_sub"`
	IdSubBidang              string `bson:"id_sub_bidang" json:"id_sub_bidang"`
	NamaSubBidang            string `bson:"nama_sub_bidang" json:"nama_sub_bidang"`
	IdSinta                  string `bson:"id_sinta" json:"id_sinta"`
	IdSilidia                string `bson:"id_silidia" json:"id_silidia"`
	TahunImplementasi        string `bson:"tahun_implementasi" json:"tahun_implementasi"`
	TahunAwal                string `bson:"tahun_awal" json:"tahun_awal"`
	TahunProposal            string `bson:"tahun_proposal" json:"tahun_proposal"`
	FileSampul               string `bson:"file_sampul" json:"file_sampul"`
	FileDaftarIsi            string `bson:"file_daftar_isi" json:"file_daftar_isi"`
	FileLembarPengesahan     string `bson:"file_lembar_pengesahan" json:"file_lembar_pengesahan"`
	FileBuktiKerja           string `bson:"file_bukti_kerja" json:"file_bukti_kerja"`
	FileProposal             string `bson:"file_proposal" json:"file_proposal"`
	FileRevisi               string `bson:"file_revisi" json:"file_revisi"`
	FileLaporanKemajuan      string `bson:"file_laporan_kemajuan" json:"file_laporan_kemajuan"`
	FileLaporanAkhir         string `bson:"file_laporan_akhir" json:"file_laporan_akhir"`
	IdSkim                   string `bson:"id_skim" json:"id_skim"`
	IdFokus                  string `bson:"id_fokus" json:"id_fokus"`
	IdHibah                  string `bson:"id_hibah" json:"id_hibah"`
	IdSosekSub               string `bson:"id_sosek_sub" json:"id_sosek_sub"`
	JenisPenelitian          string `bson:"jenis_penelitian" json:"jenis_penelitian"`
	InstitusiSumberDana      string `bson:"institusi_sumber_dana" json:"institusi_sumber_dana"`
	Dana                     string `bson:"dana" json:"dana"`
	Skema                    string `bson:"skema" json:"skema"`
	SumberData               string `bson:"sumber_data" json:"sumber_data"`
	Deskripsi                string `bson:"deskripsi" json:"deskripsi"`
	Posisi                   string `bson:"posisi" json:"posisi"`
	StatusLengkap            string `bson:"status_lengkap" json:"status_lengkap"`
	RumpunIlmu               string `bson:"rumpun_ilmu" json:"rumpun_ilmu"`
	UpdatedAt                string `bson:"updated_at" json:"updated_at"`
	DeletedAt                string `bson:"deleted_at" json:"deleted_at"`
	Komentar                 string `bson:"komentar" json:"komentar"`
	ValidIpk                 string `bson:"valid_ipk" json:"valid_ipk"`
	ValidIpkKomentar         string `bson:"valid_ipk_komentar" json:"valid_ipk_komentar"`
	BidangPenelitian         string `bson:"bidang_penelitian" json:"bidang_penelitian"`
	Skim                     string `bson:"skim" json:"skim"`
	TujuanEkonomiSosial      string `bson:"tujuan_ekonomi_sosial" json:"tujuan_ekonomi_sosial"`
	LevelCapaian             string `bson:"level_capaian" json:"level_capaian"`
	MahasiswaPenelitian      string `bson:"mahasiswa_penelitian" json:"mahasiswa_penelitian"`
	AnggotaPenelitian        string `bson:"anggota_penelitian" json:"anggota_penelitian"`
	CronTahun                string `bson:"cron_tahun" json:"cron_tahun"`
	CronSemester             string `bson:"cron_semester" json:"cron_semester"`
	DokumenPendukung         string `bson:"dokumen_pendukung" json:"dokumen_pendukung"`
	DokumenPendukungOpsional string `bson:"dokumen_pendukung_opsional" json:"dokumen_pendukung_opsional"`
	FileMitraAwal            string `bson:"file_mitra_awal" json:"file_mitra_awal"`
	Periode                  string `bson:"periode" json:"periode"`
	SemesterType             string `bson:"semester_type" json:"semester_type"`
	Unit                     Unit   `bson:"unit" json:"unit"`
}
