package models

type Prosiding struct {
	ID                    int      `bson:"_id" json:"_id"`
	JudulArtikel          string   `bson:"judul_artikel" json:"judul_artikel"`
	NamaSeminar           string   `bson:"nama_seminar" json:"nama_seminar"`
	TglAwal               string   `bson:"tgl_awal" json:"tgl_awal"`
	CreatedAt             string   `bson:"created_at" json:"created_at"`
	IsValid               string   `bson:"isValid" json:"isValid"`
	Semester              string   `bson:"semester" json:"semester"`
	TahunAjaran           string   `bson:"tahun_ajaran" json:"tahun_ajaran"`
	TbName                string   `bson:"tbName" json:"tbName"`
	PrimaryKey            string   `bson:"primaryKey" json:"primaryKey"`
	WaktuPelaksanaan      string   `bson:"waktu_pelaksanaan" json:"waktu_pelaksanaan"`
	NamaDosen             string   `bson:"nama_dosen" json:"nama_dosen"`
	Scope                 string   `bson:"scope" json:"scope"`
	TipeProsiding         string   `bson:"tipe_prosiding" json:"tipe_prosiding"`
	Tanggal               string   `bson:"tanggal" json:"tanggal"`
	IdSinta               string   `bson:"id_sinta" json:"id_sinta"`
	Penyelenggara         string   `bson:"penyelenggara" json:"penyelenggara"`
	Penerbit              string   `bson:"penerbit" json:"penerbit"`
	TglAkhir              string   `bson:"tgl_akhir" json:"tgl_akhir"`
	PIssn                 string   `bson:"P_ISSN" json:"P_ISSN"`
	EIssn                 string   `bson:"E_ISSN" json:"E_ISSN"`
	ISBN                  string   `bson:"ISBN" json:"ISBN"`
	UrlDokumen            string   `bson:"url_dokumen" json:"url_dokumen"`
	UrlPerReview          string   `bson:"url_per_review" json:"url_per_review"`
	Keterangan            string   `bson:"keterangan" json:"keterangan"`
	TempatPelaksanaan     string   `bson:"tempat_pelaksanaan" json:"tempat_pelaksanaan"`
	Satuan                string   `bson:"satuan" json:"satuan"`
	VolumeKegiatan        string   `bson:"volume_kegiatan" json:"volume_kegiatan"`
	Sinta                 string   `bson:"sinta" json:"sinta"`
	JenisPembicara        string   `bson:"jenis_pembicara" json:"jenis_pembicara"`
	Posisi                string   `bson:"posisi" json:"posisi"`
	FileUpload            string   `bson:"file_upload" json:"file_upload"`
	JmlPenulis            string   `bson:"jml_penulis" json:"jml_penulis"`
	FilePenilaianReviewer string   `bson:"file_penilaian_reviewer" json:"file_penilaian_reviewer"`
	FileHasilUjiPlagiarim string   `bson:"file_hasil_uji_plagiarim" json:"file_hasil_uji_plagiarim"`
	UpdatedAt             string   `bson:"updated_at" json:"updated_at"`
	DeletedAt             string   `bson:"deleted_at" json:"deleted_at"`
	IsProduk              string   `bson:"is_produk" json:"is_produk"`
	ProdukPenelitianJudul string   `bson:"produk_penelitian_judul" json:"produk_penelitian_judul"`
	ProdukPenelitianID    string   `bson:"produk_penelitian_id" json:"produk_penelitian_id"`
	ProdukPengabdianJudul string   `bson:"produk_pengabdian_judul" json:"produk_pengabdian_judul"`
	ProdukPengabdianID    string   `bson:"produk_pengabdian_id" json:"produk_pengabdian_id"`
	Komentar              string   `bson:"komentar" json:"komentar"`
	StatusPublish         string   `bson:"status_publish" json:"status_publish"`
	ValidIpk              string   `bson:"valid_ipk" json:"valid_ipk"`
	ValidIpkKomentar      string   `bson:"valid_ipk_komentar" json:"valid_ipk_komentar"`
	Bereputasi            string   `bson:"bereputasi" json:"bereputasi"`
	CreateDosenID         string   `bson:"create_dosen_id" json:"create_dosen_id"`
	Indexer               []string `bson:"indexer" json:"indexer"`
	SumberProduk          string   `bson:"sumber_produk" json:"sumber_produk"`
	ProdukPenelitian      string   `bson:"produk_penelitian" json:"produk_penelitian"`
	ProdukPengabdian      string   `bson:"produk_pengabdian" json:"produk_pengabdian"`
	MahasiswaPenelitian   string   `bson:"mahasiswa_penelitian" json:"mahasiswa_penelitian"`
	AnggotaPenelitian     string   `bson:"anggota_penelitian" json:"anggota_penelitian"`
	AnggotaNonDosen       string   `bson:"anggota_non_dosen" json:"anggota_non_dosen"`
	CronTahun             string   `bson:"cron_tahun" json:"cron_tahun"`
	CronSemester          string   `bson:"cron_semester" json:"cron_semester"`
	KodeTipeProsiding     string   `bson:"kode_tipe_prosiding" json:"kode_tipe_prosiding"`
	KodeScope             string   `bson:"kode_scope" json:"kode_scope"`
	Periode               string   `bson:"periode" json:"periode"`
	SemesterType          string   `bson:"semester_type" json:"semester_type"`
	Unit                  Unit     `bson:"unit" json:"unit"`
}
